### ISSUE TITLE
Missing an eventQueue so tasks can run on OpenGL thread

### ISSUE THREAD

**Issue by haroldmthyng** [UncorkedStudios/recordablesurfaceview#3]
Nice library and almost a drop-in replacement, but would be ideal to add a **queueEvent** handler and setter as that method is widely used for secondary tasks that MUST run on the OpenGL thread. The omission of this method forces devs to have to write there own event queue or potentially change a lot of code to accommodate the absence of this method. Please add in future release.

I still plan to utilize this library as otherwise it's very well written. Nice job!

**Comment by spaceLenny** [comment]
Do you have an example of what you mean here? This seems like the inverse of runOnUiThread.

Thanks for trying it out! I'm interested in this idea.

**Comment by haroldmthyng** [comment]
See this link: https://developer.android.com/reference/android/opengl/GLSurfaceView#queueEvent(java.lang.Runnable)

The event queue provides a method to run any render specific tasks that have to occur on the OpenGL thread, without having to enclose that logic within the renderer itself. Great for things like collision routines, shader updates, cloning and reinitializing 3D geometry data. It is very much like a GL version of runOnUIThread.

On Apr 26, 2018, at 10:07 AM, David Evans <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you have an example of what you mean here? This seems like the inverse of runOnUiThread.

Thanks for trying it out! I'm interested in this idea.

**Comment by spaceLenny** [comment]
Please check out branch `v1.5.0` - we've added a queueEvent call that accepts a Runnable.

**Comment by haroldmthyng** [comment]
Excellent. Will definitely take a look.

**Comment by spaceLenny** [comment]
Closing this as there's been no further activity and its been in the wild for several months.
