### ISSUE TITLE
GLSurfaceView support

### ISSUE THREAD

**Issue by dbof10** [UncorkedStudios/recordablesurfaceview#5]
I want to record on my GLSurfaceView instead of SurfaceView. I tried to change my View to SurfaceView. It has some weird render state. I think I stick to my GLSurfaceView.  Do you have any instruction for this?

**Comment by spaceLenny** [comment]
Please provide more detail. Not sure this is a bug.

**Comment by LyCharlie** [comment]
recordablesurfaceview extends SurfaceView now ,if my view extends GLSurfaceView,and I want to record this view, I can't use recordablesurfaceview,  what should I do

**Comment by spaceLenny** [comment]
Why can't you use it? The example project uses it exactly like you're describing.

**Comment by LyCharlie** [comment]
Thank you for your answer. Actually I use third part [surfaceView](https://github.com/Rajawali/Rajawali/blob/master/rajawali/src/main/java/org/rajawali3d/view/SurfaceView.java) to render my view, so I can't use RecordableSurfaceView directly or extends it, MyGLSurfaceView in example project seems don't work either :(
